source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

workspace 'eWAYPaymentsSDK.xcworkspace'
xcodeproj 'eWAYPaymentsSDK.xcodeproj'
xcodeproj 'eWAYPaymentsSDK+ApplePay.xcodeproj'

target 'eWAYPaymentsSDK_Example', :exclusive => true do
  pod "eWAYPaymentsSDK", :path => "../"
  xcodeproj 'eWAYPaymentsSDK.xcodeproj'
end


target 'eWAYPaymentsSDK_Tests', :exclusive => true do
  pod "eWAYPaymentsSDK", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  xcodeproj 'eWAYPaymentsSDK.xcodeproj'
end

target 'eWAYPaymentsSDK_ApplePay_Example', :exclusive => true do
  pod "eWAYPaymentsSDK", :path => "../"
  xcodeproj 'eWAYPaymentsSDK+ApplePay.xcodeproj'
end